#Requires -Version 5.1
<#
.SYNOPSIS
    Docker Compose deploy for WeatherApp (.deploy/local or .deploy/development).
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$DeployConfigDirectory,

    [switch]$IncludeDevServices,

    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$DockerComposeArgs = @()
)

$ErrorActionPreference = "Stop"

$DockerComposeArgs = @(
    foreach ($a in $DockerComposeArgs) {
        if ($null -ne $a -and -not [string]::IsNullOrWhiteSpace([string]$a)) { [string]$a }
    }
)

$DeployConfigDirectory = (Resolve-Path -LiteralPath $DeployConfigDirectory).Path
$DeployParent = Split-Path -Parent $DeployConfigDirectory
$ProjectRoot = Split-Path -Parent $DeployParent

Set-Location $ProjectRoot

$DeployEnvFile = Join-Path $DeployConfigDirectory ".env"
$DeployEnvExample = Join-Path $DeployConfigDirectory ".env.example"
$ProjectEnvFile = Join-Path $ProjectRoot ".env"
$DeployNetworkTail = Join-Path $DeployConfigDirectory "docker-compose.deploy-network.yml"
$SharedCompose = Join-Path $ProjectRoot "docker-compose.shared.yml"
$ServiceRoot = Join-Path $ProjectRoot "src\services"

function ConvertTo-WSLPath {
    param([string]$WindowsPath)
    if ([string]::IsNullOrWhiteSpace($WindowsPath)) { return $WindowsPath }
    if ($WindowsPath -match '^([A-Z]):\\(.+)') {
        $drive = $Matches[1].ToLower()
        $rest = $Matches[2] -replace '\\', '/'
        return "/mnt/$drive/$rest"
    }
    return $WindowsPath
}

function Ensure-RootWslPathInEnvFile {
    param([string]$EnvFileFullPath, [string]$RootWslPath)
    if ([string]::IsNullOrWhiteSpace($RootWslPath)) { return }
    if (-not (Test-Path $EnvFileFullPath)) { return }
    $content = Get-Content -Path $EnvFileFullPath -Raw
    if ($content -match 'ROOT_WSL_PATH\s*=') { return }
    $comment = "# Project root in WSL format (auto-generated by Deploy-WeatherApp.ps1)"
    Add-Content -Path $EnvFileFullPath -Value "`n$comment`nROOT_WSL_PATH=$RootWslPath" -Encoding UTF8
    Write-Host "Added ROOT_WSL_PATH to $EnvFileFullPath" -ForegroundColor Cyan
}

function Read-DeployEnvValue {
    param([string]$Path, [string]$Key, [string]$Default)
    if (-not (Test-Path $Path)) { return $Default }
    $keyEsc = [regex]::Escape($Key)
    foreach ($line in Get-Content $Path) {
        if ($line -match "^\s*$keyEsc\s*=\s*(.+)$") {
            return $Matches[1].Trim().Trim('"').Trim("'")
        }
    }
    return $Default
}

if (-not (Test-Path $DeployEnvFile)) {
    if (Test-Path $DeployEnvExample) {
        Copy-Item $DeployEnvExample $DeployEnvFile
        Write-Host "Created $DeployEnvFile from .env.example" -ForegroundColor Yellow
    } else {
        Write-Error "Missing $DeployEnvExample and $DeployEnvFile"
        exit 1
    }
}

$DockerProfile = Read-DeployEnvValue -Path $DeployEnvFile -Key "WEATHERAPP_DOCKER_PROFILE" -Default "local"
if ([string]::IsNullOrWhiteSpace($DockerProfile)) { $DockerProfile = "local" }

$NetworkName = Read-DeployEnvValue -Path $DeployEnvFile -Key "WEATHERAPP_NETWORK_NAME" -Default "vs-weatherapp-local-network"

$RootWslPath = ConvertTo-WSLPath $ProjectRoot
Ensure-RootWslPathInEnvFile -EnvFileFullPath $ProjectEnvFile -RootWslPath $RootWslPath

function Get-ServiceNamesWithCompose {
    param([string]$Profile)
    $names = @()
    foreach ($dir in (Get-ChildItem -Path $ServiceRoot -Directory -ErrorAction SilentlyContinue)) {
        $compose = Join-Path $dir.FullName (Join-Path (Join-Path ".docker" $Profile) "docker-compose.yml")
        if (Test-Path $compose) {
            $names += $dir.Name
        }
    }
    return $names | Sort-Object
}

$servicesFilter = Read-DeployEnvValue -Path $DeployEnvFile -Key "WEATHERAPP_SERVICES" -Default "*"
$allAvailable = @(Get-ServiceNamesWithCompose -Profile $DockerProfile)
if ([string]::IsNullOrWhiteSpace($servicesFilter) -or $servicesFilter -eq "*") {
    $selectedNames = $allAvailable
} else {
    $wanted = $servicesFilter -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    $selectedNames = @()
    foreach ($w in $wanted) {
        if ($allAvailable -contains $w) {
            $selectedNames += $w
        } else {
            Write-Warning "WEATHERAPP_SERVICES entry '$w' skipped."
        }
    }
}

if ($selectedNames.Count -eq 0) {
    Write-Error "No services selected. Check WEATHERAPP_SERVICES in $DeployEnvFile (available: $($allAvailable -join ', '))."
    exit 1
}

$ServiceComposeFiles = @()
foreach ($svcName in $selectedNames) {
    $profileDir = Join-Path $ServiceRoot (Join-Path $svcName (Join-Path ".docker" $DockerProfile))
    $main = Join-Path $profileDir "docker-compose.yml"
    if (Test-Path $main) {
        $ServiceComposeFiles += $main
    }
    if ($IncludeDevServices) {
        $dev = Join-Path $profileDir "docker-compose.dev.yml"
        if (Test-Path $dev) {
            $ServiceComposeFiles += $dev
        }
    }
}

if ($ServiceComposeFiles.Count -eq 0) {
    Write-Error "No compose files resolved for profile '$DockerProfile'."
    exit 1
}

if (-not (Test-Path $SharedCompose)) {
    Write-Error "Missing shared compose: $SharedCompose"
    exit 1
}
if (-not (Test-Path $DeployNetworkTail)) {
    Write-Error "Missing network file: $DeployNetworkTail"
    exit 1
}

$ComposeFiles = @("-f", $SharedCompose)
foreach ($f in $ServiceComposeFiles) {
    $ComposeFiles += "-f"
    $ComposeFiles += $f
}
$ComposeFiles += "-f"
$ComposeFiles += $DeployNetworkTail

$envFiles = @("--env-file", $DeployEnvFile)
if (Test-Path $ProjectEnvFile) {
    $envFiles += "--env-file"
    $envFiles += $ProjectEnvFile
}

$deployLabel = Split-Path -Leaf $DeployConfigDirectory

if ($DockerComposeArgs.Count -eq 0) {
    Write-Host "`nWeatherApp deploy ($deployLabel)" -ForegroundColor Cyan
    Write-Host "Project: $ProjectRoot"
    Write-Host "Deploy env: $DeployEnvFile"
    Write-Host "Profile: $DockerProfile | Network: $NetworkName`n" -ForegroundColor Gray
    Write-Host "Services: $($selectedNames -join ', ')" -ForegroundColor Gray
    Write-Host "Compose files: $SharedCompose + service files + $DeployNetworkTail" -ForegroundColor Gray
    exit 0
}

$allArgs = @("compose", "--project-directory", $ProjectRoot) + $envFiles + $ComposeFiles + $DockerComposeArgs
Write-Host "docker compose ... $($DockerComposeArgs -join ' ')" -ForegroundColor Cyan

$firstCmd = if ($DockerComposeArgs.Count -gt 0) { $DockerComposeArgs[0].ToLowerInvariant() } else { "" }
if ($firstCmd -eq "up" -or $firstCmd -eq "create") {
    $prevEa = $ErrorActionPreference
    $ErrorActionPreference = "SilentlyContinue"
    docker network inspect $NetworkName 2>&1 | Out-Null
    $ErrorActionPreference = $prevEa
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Creating Docker network: $NetworkName" -ForegroundColor Cyan
        docker network create $NetworkName
    }
}

$env:DOCKER_BUILDKIT = "0"
& docker $allArgs
exit $LASTEXITCODE
